import React from 'react';
import ReactDOM from 'react-dom';
import '../setupTests.js';
import { configure, mount } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import TabContent from './TabContent.js';

configure({ adapter: new Adapter() });

const testJson=[
    {  
        "key":"fall",
        "ref":null,
        "props":{  
           "season":"fall",
           "schedules":[  
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              },
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              },
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              }
           ]
        },
        "_owner":null,
        "_store":{  
     
        }
     },
     {  
        "key":"winter",
        "ref":null,
        "props":{  
           "season":"winter",
           "schedules":[  
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              },
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              },
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              }
           ]
        },
        "_owner":null,
        "_store":{  
     
        }
     },
     {  
        "key":"summer",
        "ref":null,
        "props":{  
           "season":"summer",
           "schedules":[  
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              },
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              },
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              }
           ]
        },
        "_owner":null,
        "_store":{  
     
        }
     },
     {  
        "key":"fall",
        "ref":null,
        "props":{  
           "season":"fall",
           "schedules":[  
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              },
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              },
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              }
           ]
        },
        "_owner":null,
        "_store":{  
     
        }
     },
     {  
        "key":"winter",
        "ref":null,
        "props":{  
           "season":"winter",
           "schedules":[  
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              },
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              },
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              }
           ]
        },
        "_owner":null,
        "_store":{  
     
        }
     },
     {  
        "key":"summer",
        "ref":null,
        "props":{  
           "season":"summer",
           "schedules":[  
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              },
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              },
              {  
                 "courseId1":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId2":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 },
                 "courseId3":{  
                    "lecture":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "lab":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    },
                    "tutorial":{  
                       "time_start":"8:45",
                       "time_end":"10:00",
                       "days":"TuTh"
                    }
                 }
              }
           ]
        },
        "_owner":null,
        "_store":{  
     
        }
     }
     ];
describe('TabContent', () => {
    it('renders without crashing', () => {
        const wrapper = mount(<TabContent scheduleComponents={JSON.stringify(testJson)}/>);
        expect(wrapper.length).toBe(1);
    });
});
